### ISSUE TITLE
Build error: drm/drm_fourcc.h: No such file or directory

### ISSUE THREAD

**Issue by dbermond** [intel/gstreamer-media-SDK#121]
I'm getting the following compile error when trying to build.

When using the git master branch with cmake, the error is:
```
[ 79%] Building C object CMakeFiles/gstmfx.dir/gst-libs/mfx/egl/gstmfxtexture_egl.c.o
/storage/linux/abs/gst-plugins-intel-msdk-git/src/gst-plugins-intel-msdk-git/gst-libs/mfx/egl/gstmfxtexture_egl.c:25:10: fatal error: drm/drm_fourcc.h: No such file or directory
 #include <drm/drm_fourcc.h>
          ^~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/gstmfx.dir/build.make:596: CMakeFiles/gstmfx.dir/gst-libs/mfx/egl/gstmfxtexture_egl.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:100: CMakeFiles/gstmfx.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
```

In the master branch, this fixes the issue for me:
```diff
diff --git a/gst-libs/mfx/egl/gstmfxtexture_egl.c b/gst-libs/mfx/egl/gstmfxtexture_egl.c
index 8a1c672..902c6d9 100644
--- a/gst-libs/mfx/egl/gstmfxtexture_egl.c
+++ b/gst-libs/mfx/egl/gstmfxtexture_egl.c
@@ -22,7 +22,7 @@
 
 #include "sysdeps.h"
 
-#include <drm/drm_fourcc.h>
+#include <libdrm/drm_fourcc.h>
 #include "gstmfxtexture_egl.h"
 #include "gstmfxutils_egl.h"
 #include "gstmfxsurface_vaapi.h"
```

When using the [topic_linux_and_window](https://github.com/intel/gstreamer-media-SDK/tree/topic_linux_and_window) branch with meson, the error is:
```
[32/45] Compiling C object 'gst/mfx/gst@mfx@@gstmfx@sha/gstmfxpluginbase.c.o'.
FAILED: gst/mfx/gst@mfx@@gstmfx@sha/gstmfxpluginbase.c.o 
cc -Igst/mfx/gst@mfx@@gstmfx@sha -Igst/mfx -I../gst/mfx -I. -I../ -Igst-libs/mfx -I../gst-libs/mfx -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/gstreamer-1.0 -I/usr/include/orc-0.4 -I/opt/intel/mediasdk/include -I/usr/include/libdrm -I/usr/lib/gstreamer-1.0/include -flto -fdiagnostics-color=always -pipe -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -O3 -march=x86-64 -mtune=generic -O2 -fstack-protector-strong -fno-plt -D_FORTIFY_SOURCE=2 -fPIC -pthread -DWITH_LIBVA_BACKEND -DHAVE_GST_GL_LIBS -DGST_USE_UNSTABLE_API -DMFX_DECODER -DUSE_WAYLAND -DUSE_DRI3 -DHAVE_XKBLIB -DHAVE_XRANDR -DMFX_SINK -DMFX_VPP -DMFX_SINK_BIN -DMFX_H264_ENCODER -DMFX_JPEG_ENCODER  -MD -MQ 'gst/mfx/gst@mfx@@gstmfx@sha/gstmfxpluginbase.c.o' -MF 'gst/mfx/gst@mfx@@gstmfx@sha/gstmfxpluginbase.c.o.d' -o 'gst/mfx/gst@mfx@@gstmfx@sha/gstmfxpluginbase.c.o' -c ../gst/mfx/gstmfxpluginbase.c
../gst/mfx/gstmfxpluginbase.c:49:11: fatal error: drm/drm_fourcc.h: No such file or directory
 # include <drm/drm_fourcc.h>
           ^~~~~~~~~~~~~~~~~~
compilation terminated.
ninja: build stopped: subcommand failed.
```

In the [topic_linux_and_window](https://github.com/intel/gstreamer-media-SDK/tree/topic_linux_and_window) branch, this fixes the issue for me:
```diff
diff --git a/gst/mfx/gstmfxpluginbase.c b/gst/mfx/gstmfxpluginbase.c
index 7beeb88..1f92763 100644
--- a/gst/mfx/gstmfxpluginbase.c
+++ b/gst/mfx/gstmfxpluginbase.c
@@ -46,7 +46,7 @@
 #ifdef WITH_LIBVA_BACKEND
 # include <EGL/egl.h>
 # include <EGL/eglext.h>
-# include <drm/drm_fourcc.h>
+# include <libdrm/drm_fourcc.h>
 
 # include <gst/gl/egl/gstgldisplay_egl.h>
 
```

**System Information:**
**OS:** Arch Linux x86_64
**Compiler:** gcc 8.2.0
**cmake:** 3.11.4
**meson:** 0.47.1
**ninja:** 1.8.2
**gstreamer:** 1.14.2
**intel-media-sdk:** 2018.Q2.2
**libdrm:** 2.4.93
**libva:** 2.2.0

**Comment by dbermond** [comment]
@ishmael1985 Thank you. I have created pull requests to fix both branches.

**Comment by SiewHoon** [comment]
I would like to understand more details first before I accept this patch.  

How you encounter the build error? Is this due to configuration file in gst-msdk or is it because your system does not have the kernel header file that causing the compilation error. 

usr/include/drm/drm_fourcc.h -  it is coming from kernel header. 
usr/include/libdrm/drm_fourcc.h - it is coming from libdrm

**Comment by dbermond** [comment]
@SiewHoon Thank you for the reply. My system have the  `drm_fourcc.h` header provided by linux-headers, but it's located in a different directory than yours:

```
$ find /usr -type f -name 'drm_fourcc.h' 2>/dev/null
/usr/lib/modules/4.18.4-arch1-1-ARCH/build/include/drm/drm_fourcc.h
/usr/lib/modules/4.18.4-arch1-1-ARCH/build/include/uapi/drm/drm_fourcc.h
/usr/include/libdrm/drm_fourcc.h
```

As you can see, it's not located in `$includedir/drm` as the build system expects.

More details can be seen in the Package Contents (file list) section of the [linux-headers](https://www.archlinux.org/packages/core/x86_64/linux-headers/) packages from Arch.

**Comment by ishmael1985** [comment]
@dbermond your patch looks good to me in my book, it's better to use the user-space drm_fourcc.h compared to kernel-space drm_fourcc.h which could be located in non-standard paths. I have seen the same employed in this here - https://cgit.freedesktop.org/gstreamer/gst-plugins-base/tree/gst-libs/gst/gl/egl/gsteglimage.c

**Comment by SiewHoon** [comment]
@ishmael1985 you only focus on fix compilation error fixed causing by drm_fourcc.h.  On my side, I would prefer to standardized the header file use inside gst-msdk source code touch on drm/header file before replace to libdrm/header file. Not just focus on fix one drm_fourcc.h header inside the code.

@dbermond what is the OS that you are using on your system? Are you building your own kernel ?

**Comment by ishmael1985** [comment]
@SiewHoon libdrm has included drm_fourcc.h since 2011 - https://cgit.freedesktop.org/mesa/drm/commit/include/drm/drm_fourcc.h?h=2.4.36&id=ac168bf2a068761b591187e6a0a52083d456280b
It's already standard, which is why GstGL from gst-plugins-base mainline uses this header path instead, see here - https://cgit.freedesktop.org/gstreamer/gst-plugins-base/tree/gst-libs/gst/gl/egl/gsteglimage.c
The point of this patch is to mitigate the chances of gst-msdk build breaking if the kernel-space drm_fourcc.h header file is located in a non-standard location. With the user-space drm_fourcc.h header file, you have pkg-config to help find that header file for you.

**Comment by SiewHoon** [comment]
@ishmael1985 I known. I already mention at here. I would like to fix not just drm_fourcc.h. Also other header file such as #include <drm.h> as well. I would prefer to standardized its.  Thank you.

**Comment by ishmael1985** [comment]
@SiewHoon sorry if I had misunderstood the original intention of what you were trying to say.
Is it possible for you to merge not just one PR for master but also for topic_linux_and_window branch?
You also should not close the issue yourself, it should be @dbermond who should close it, if he thinks the issue is fully resolved on his side. Is it ok for you that this issue is closed, @dbermond ?

**Comment by dbermond** [comment]
@SiewHoon Thank you for implementing this. Any hope for the fix to be also implemented in the topic_linux_and_window branch?

I'm running Arch Linux x86_64 (see initial post).
